name: Check pacman recipe and modify versions if necessary

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
    - '.github/workflows/update_version.yml'

jobs:
  checkupdate:
    runs-on: ubuntu-latest
    env:
      RECIPE: PKGBUILD
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Check latest version
      id: latest-version
      run: |
        echo ::set-output name=latest::$(curl -s https://app.datafy.cloud/api/info/cli/version)

    - name: Check current version
      id: current-version
      run: |
        echo ::set-output name=current::$(grep "pkgver=.*" $RECIPE | grep -o "[0-9]*\.[0-9]*.[0-9]*")
        
    - name: Check if they are the same
      id: same-version
      run: |
        current=${${{ steps.current-version.current }}}
        latest=${${{ steps.latest-version.latest }}}
        echo $latest
        echo $current
        echo ::set-output name=same::$(if [ $latest == $current ]; then echo 'true'; else echo 'false'; fi)

    - name: Modify recipe if they are different
      if: steps.same-version.same == 'false'
      run: |
        version=${${{ steps.latest-version.latest }}}
        old_version=${${{ steps.current-version.current }}}
        pathlinux=datafy_linux.tar.gz
        curl -sL https://datafy-cp-artifacts.s3-eu-west-1.amazonaws.com/cli/${version}/datafy_linux_amd64.tar.gz -o $pathlinux
        sli=($(sha256sum $pathlinux))
        sli=${sli[0]}
        DFSHASUM=$sli DFVERSION=$version envsubst < PKGBUILD-infotemplate > temp_info
        cat temp_info PKGBUILD_actiontemplate > PKGBUILD
        rm $pathlinux temp_info

    - name: Trigger a pull request if something changed
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Updated from version ${{ steps.current-version.current }} to ${{ steps.latest-version.latest }}
